name: Testing GitHub Actions

on:
  push:
    branches: ["master"]

jobs:
  install-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get yarn cache directory path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install packages
        run: yarn install

  build-app:
    needs: [install-packages]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get yarn cache directory path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install packages
        run: yarn install
      - name: build app
        run: yarn build
        